apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
   name: catapp-build-and-deploy
spec:
   serviceAccountName: pipeline
   pipelineRef:
     name: build-and-deploy-openshift
   resources:
   - name: source
     resourceSpec:
       type: git
       params:
       - name: revision
         value: main
       - name: url
         value: https://github.ibm.com/soukaina-khalkhouli/tekton-cicd
   - name: image
     resourceSpec:
       type: image
       params:
       - name: url
         value: image-registry.openshift-image-registry.svc:5000/catapp/tekton-cicd:main
   params:
   - name: DEPLOYMENT
     value: catapp